In [5]:
import numpy as np

In [6]:
data1 = np.array([1,2,3])
print(data1)

[1 2 3]


In [7]:
data2 = np.array([[1,2,3],[4,5,6]])
data2

array([[1, 2, 3],
       [4, 5, 6]])

### Numpy Operations

In [9]:
data2 = np.array([[1,2,3],[4,5,6]])
data2.ndim

2

In [10]:
data2 = np.array([[1,2,3],[4,5,6]])
data2.itemsize

8

In [11]:
data2 = np.array([[1,2,3],[4,5,6]])
data2.dtype

dtype('int64')

In [12]:
data2 = np.array([[1,2,3],[4,5,6]])
data2.size

6

In [13]:
data2 = np.array([[1,2,3],[4,5,6]])
data2.shape

(2, 3)

In [14]:
data2 = np.array([[1,2,3],[4,5,6]])
data2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
data2 = np.array([[1,2,3],[4,5,6]])
data2.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
data2 = np.array([[1,2,3],[4,5,6]])
data2[0,2]

3

In [18]:
data2 = np.array([[1,2,3],[4,5,6]])
data2[0:,2]

array([3, 6])

In [19]:
data2 = np.array([[1,2],[3,4],[5,6]])
print(data2)

[[1 2]
 [3 4]
 [5 6]]


In [20]:
data2 = np.array([[1,2],[3,4],[5,6]])
data2[0:2,1]

array([2, 4])

In [24]:
data = np.linspace(1,3,10)
data               

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [25]:
data = np.array([[1,2],[3,4],[5,6]])
data.max()

6

In [26]:
data = np.array([[1,2],[3,4],[5,6]])
data.min()

1

In [27]:
data = np.array([[1,2],[3,4],[5,6]])
data.sum()

21

In [28]:
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
data = np.array([[1,2],[3,4],[5,6]])
data.sum(axis=0)

array([ 9, 12])

In [30]:
data = np.array([[1,2],[3,4],[5,6]])
data.sum(axis=1)

array([ 3,  7, 11])

In [31]:
data = np.array([[1,2],[3,4],[5,6]])
np.sqrt(data)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [32]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[4,9,6,],[9,7,0]])
print(x)
print(y)

[[1 2 3]
 [4 5 6]]
[[4 9 6]
 [9 7 0]]


In [33]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[4,9,6,],[9,7,0]])
x
y

array([[4, 9, 6],
       [9, 7, 0]])

In [34]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[4,9,6,],[9,7,0]])
x y

SyntaxError: invalid syntax (<ipython-input-34-f437e25f6db3>, line 3)

In [35]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[4,9,6,],[9,7,0]])
print(x) print(y)

SyntaxError: invalid syntax (<ipython-input-35-d35098cbfd11>, line 3)

In [36]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[4,9,6,],[9,7,0]])
x+y

array([[ 5, 11,  9],
       [13, 12,  6]])

In [37]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[4,9,6,],[9,7,0]])
x-y

array([[-3, -7, -3],
       [-5, -2,  6]])

In [38]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[4,9,6,],[9,7,0]])
x*y

array([[ 4, 18, 18],
       [36, 35,  0]])

In [39]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[4,9,6,],[9,7,0]])
x/y

/Users/kayshahbaaz/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([[0.25      , 0.22222222, 0.5       ],
       [0.44444444, 0.71428571,        inf]])

### Vertical stacking and Horizontal stacking

In [41]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[4,9,6,],[9,7,0]])
np.vstack((x,y))

array([[1, 2, 3],
       [4, 5, 6],
       [4, 9, 6],
       [9, 7, 0]])

In [42]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[4,9,6,],[9,7,0]])
np.hstack((x,y))

array([[1, 2, 3, 4, 9, 6],
       [4, 5, 6, 9, 7, 0]])

Refrence: Edureka_youtube